name: "oaiaux"

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ^1.18
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Test
      run: |
        go test -v -timeout 9999s -count 1 -p 1 -cover -coverprofile coverage.txt .
    - name: Codecov
      uses: codecov/codecov-action@v3
